name: stage_4
loaders:
  asr_s2tt:
    weight: 0.1
    task_weights:
      asr: 0.5
      s2tt: 0.5
  tts_t2st:
    weight: 0.1
    task_weights:
      tts: 0.5
      t2st: 0.5
  s2st:
    weight: 0.7
    task_weights:
      s2st: 1.0
  mt:
    weight: 0.1
    task_weights:
      mt: 1.0
batches_per_step: 10
