accelerator: gpu
devices: auto
strategy: ddp_find_unused_parameters_true
use_distributed_sampler: true
precision: bf16-mixed
max_epochs: -1
log_every_n_steps: 10
enable_checkpointing: true
gradient_clip_val: 1.0
