accelerator: gpu
devices: 2
strategy: ddp_find_unused_parameters_true
expected_world_size: 2
use_distributed_sampler: false
precision: 32-true
max_epochs: 1
log_every_n_steps: 1
enable_checkpointing: true
gradient_clip_val: 1.0
