defaults:
  - /callback@callbacks.checkpoint: checkpoint
  - /callback@callbacks.learning_rate_monitor: learning_rate_monitor
  - /callback@callbacks.sample: sample
  - /callback@callbacks.generation: generation
  - _self_

name: wmt19-mixed-smoke
default_root_dir: null
accelerator:
devices: auto
strategy: auto
gradient_clip_val: 1.0
gradient_clip_algorithm: norm
ckpt_path:
log_every_n_steps:
enable_model_summary: true
enable_progress_bar: true
