"""Shared task, modality, and routing contracts."""

from .contract import (
    ControlToken,
    FieldRole,
    PredictionModality,
    Request,
    ResponseControl,
    ResponseControlTokens,
    ResponseLayout,
    ResponseSpec,
    ResponseStep,
    SourceLayout,
    Task,
    TaskField,
    TaskObjective,
    TaskProgram,
    execution_signature,
    normalize_language_code,
    response_control_tokens,
    resolve_response,
    uses_source_ctc,
    uses_target_ctc,
)
from .program import DIRECT, FULL_COT, PROGRAMS, TARGET_COT, program_for

__all__ = [
    "ControlToken",
    "DIRECT",
    "FULL_COT",
    "FieldRole",
    "PROGRAMS",
    "PredictionModality",
    "Request",
    "ResponseControl",
    "ResponseControlTokens",
    "ResponseLayout",
    "ResponseSpec",
    "ResponseStep",
    "SourceLayout",
    "TARGET_COT",
    "Task",
    "TaskField",
    "TaskObjective",
    "TaskProgram",
    "execution_signature",
    "normalize_language_code",
    "program_for",
    "resolve_response",
    "response_control_tokens",
    "uses_source_ctc",
    "uses_target_ctc",
]
