codec: bicodec
bicodec_revision: 642071559bfc6346c2359d19dcb6be3f9dd8a05d
backbone: Qwen/Qwen3-0.6B
backbone_initialization: pretrained
audio_tokenizer:
semantic_codec_artifact:
device: cuda
dtype: bfloat16
attn_implementation: flash_attention_2
gradient_checkpointing: true
flow_method: midpoint
flow_nfe: 20
flow_num_steps: 10
