defaults:
  - experiment: overfit
  - callback/performance@callbacks.performance
  - _self_

repo_output_root: ${oc.env:SPEECH_TO_SPEECH_TRAIN_ROOT,${oc.env:DYNAMIC_HOME}/train/speech-to-speech}
output_dir: ${repo_output_root}/${output_subdir}

callbacks:
  performance:
    enabled: false

hydra:
  job:
    chdir: false
  run:
    dir: ${output_dir}/hydra
  output_subdir: config
